services:
  postgres:
    image: postgres:15
    container_name: Techcore_Internship_Postgres_Container
    environment:
      POSTGRES_DB: Techcore_Internship_Postgres
      POSTGRES_USER: Cruciatus
      POSTGRES_PASSWORD: 12345qwerty
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - Postgres_Data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: Techcore_Internship_Redis_Container
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - Redis_Data:/data
    command: redis-server --appendonly yes

  mongo:
    image: mongo:7.0
    container_name: Techcore_Internship_Mongo_Container
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: Cruciatus
      MONGO_INITDB_ROOT_PASSWORD: 12345qwerty
    volumes:
      - Mongo_Data:/data/db
      - Mongo_Config:/data/configdb

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: Techcore_Internship_RabbitMQ_Container
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: Cruciatus
      RABBITMQ_DEFAULT_PASS: 12345qwerty
    volumes:
      - RabbitMQ_Data:/var/lib/rabbitmq

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: Techcore_Internship_Zookeeper_Container
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: always
    ports:
      - "2181:2181"
    volumes:
      - Zookeeper_Data:/var/lib/zookeeper/data
      - Zookeeper_Log:/var/lib/zookeeper/log

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: Techcore_Internship_Kafka_Container
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    restart: always
    ports:
      - "9092:9092"
    volumes:
      - Kafka_Data:/var/lib/kafka/data

volumes:
  Postgres_Data:
  Redis_Data:
  Mongo_Data:
  Mongo_Config:
  RabbitMQ_Data:
  Zookeeper_Data:
  Zookeeper_Log:
  Kafka_Data: